services:
  file-server:
    build: .
    container_name: file-server
    ports:
      - "${HOST:-0.0.0.0}:${PORT:-5000}:5000"
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH:-104857600}
      - DEFAULT_SHARE_DAYS=${DEFAULT_SHARE_DAYS:-7}
      - SHARE_HOST=${SHARE_HOST:-http://localhost:5000}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - ENABLE_FILE_TYPE_CHECK=${ENABLE_FILE_TYPE_CHECK:-false}
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance
    restart: unless-stopped